### PR TITLE
fix skins

### PR DESCRIPTION
**Pull request by MrDoni98**
This request corrects an error due to which the npc did not save the skin after the server rebooted.
The second parameter of the Skin() requires a skinData(), you transmit the eid.
Thanks

### CODE REVIEW

**Comment by onebone** [comment]
It seems that it will break compatibility with the data file from previous versions.

Why did you save skin data in both .skin file and .json though skin data in .skin file is not being used?

**Comment by MrDoni98** [comment]
.json?

**Comment by onebone** [comment]
Sorry, I mean .dat file.

**Comment by MrDoni98** [comment]
oh, yes. sorry) I'll fix it now

**Comment by MrDoni98** [comment]
Checked

**Comment by onebone** [comment]
Great, thanks for your contribution!

**Pull request merged**
